openapi: 3.0.1
info:
  title: IATI Validator
  description: "IATI Validation API. Provides routes related to the validation of IATI XML.\n\nThe API adheres to the [IATI Validator API Contract](https://cdn.iatistandard.org/prod-iati-website/documents/IATI_Validator_API_Contract.pdf)."
  version: '1.0'
servers:
  - url: https://dev-api.iatistandard.org/validator
paths:
  /report:
    get:
      tags:
        - validator
        - GET
      summary: Existing Report
      description: "Get an existing validation report of a published IATI document known to the IATI Registry by passing either the id, hash or URL of the document, as available from the Registry API.\n\n[GitHub Repository](https://github.com/IATI/validator-services)\n\n[Error ID Information](https://github.com/IATI/validator-rule-tracker)\n"
      operationId: get-pub-get-report
      parameters:
        - name: id
          in: query
          description: 'id of the published document for which you want a validation report, as provided by the Registry API'
          schema:
            type: string
        - name: url
          in: query
          description: 'url of the published document for which you want a validation report, as provided by the Registry API'
          schema:
            type: string
        - name: hash
          in: query
          description: 'hash of the published document for which you want a validation report, as provided by the Registry API'
          schema:
            type: string
        - name: showerrors
          in: query
          description: 'If set to false, the detailed errors of the validation report will not be returned. Default is true and detailed validation errors are returned. This parameter is useful to save on response body size if you are not using the full validation report errors.'
          schema:
            enum:
              - false
              - true
            type: boolean
        - name: Accept
          in: header
          schema:
            enum:
              - application/json
            type: string
            default: application/json
      responses:
        '422':
          description: 'Response if id, url or hash is not provided as a query parameter.'
          headers:
            Content-Type:
              description: content type of the response
              required: true
              schema:
                enum:
                  - application/json
                type: string
                default: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Existing Report missing query parameter'
              example:
                client_error: 'Either the id, url or hash of the document as obtained from the IATI Registry must be supplied as a GET parameter'
        '404':
          description: 'Response if a report cannot be found for the supplied id, url or hash.'
          headers:
            Content-Type:
              description: content type of response
              required: true
              schema:
                enum:
                  - application/json
                type: string
                default: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Existing Report Not Found'
              example:
                client_error: The requested report does not exist.
        '200':
          description: Response if a report is found and returned.
          headers:
            Content-Type:
              description: content type of the response
              required: true
              schema:
                enum:
                  - application/json
                type: string
                default: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Validation Report Published File'
              example:
                registry_hash: string
                registry_id: string
                document_url: string
                valid: false
                report:
                  valid: false
                  fileType: string
                  iatiVersion: string
                  rulesetCommitSha: string
                  codelistCommitSha: string
                  orgIdPrefixFileName: string
                  apiVersion: string
                  summary:
                    critical: 0
                    error: 0
                    warning: 0
                  errors:
                    - errors:
                        - errors:
                            - id: string
                              severity: string
                              message: string
                              codelist: string
                              context:
                                - text: string
                          category: string
                      identifier: string
                      title: string
  /validate:
    post:
      tags:
        - validator
        - POST
      summary: Validate
      description: "This route allows the user to POST an IATI document to the Validator in the body of the request, and receive a JSON validation report in the response.\n\n[GitHub Repository](https://github.com/IATI/js-validator-api)  \n\n[Error ID Information](https://github.com/IATI/validator-rule-tracker)\n"
      operationId: post-pub-validate-post
      parameters:
        - name: group
          in: query
          description: group errors by activity (or organisation) and category. Defaults to true if left blank. Set to false to ungroup errors.
          schema:
            enum:
              - 'true'
              - 'false'
            type: string
        - name: details
          in: query
          description: 'show all available details of errors. Defaults to false if left blank. Set to true to see all details. '
          schema:
            enum:
              - 'false'
              - 'true'
            type: string
        - name: Content-Type
          in: header
          description: Indicates the content type of the request body
          required: true
          schema:
            enum:
              - application/xml
            type: string
        - name: Accept
          in: header
          required: true
          schema:
            enum:
              - application/json
            type: string
            default: application/json
      requestBody:
        description: IATI XML document (organisations or activities)
        content:
          application/xml: { }
          application/json: { }
          text/plain: { }
          text/xml: { }
      responses:
        '400':
          description: The body is either not present or is malformed.
          headers:
            Content-Type:
              description: content type
              schema:
                enum:
                  - application/json
                type: string
                default: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/No Body Error'
              example:
                error: No body
        '422':
          description: "Content of the body can be interpreted by the application but doesn't make sense for one of the following reasons.\n- Not recognisable as IATI\n- Critical (Schema) Errors\n- Not a supported version of IATI"
          headers:
            Content-Type:
              description: content type
              schema:
                enum:
                  - application/json
                type: string
                default: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Validation Report Ad Hoc Validate'
              example:
                valid: false
                fileType: string
                iatiVersion: string
                rulesetCommitSha: string
                codelistCommitSha: string
                orgIdPrefixFileName: string
                apiVersion: string
                summary:
                  critical: 0
                  error: 0
                  warning: 0
                errors:
                  - errors:
                      - errors:
                          - id: string
                            severity: string
                            message: string
                            codelist: string
                            context:
                              - text: string
                        category: string
                    identifier: string
                    title: string
        '200':
          description: No Critical errors were detected with the IATI document and validation was successful. There may be validation errors of severity "error" or "warning" with the document.
          headers:
            Content-Type:
              description: content type
              schema:
                enum:
                  - application/json
                type: string
                default: application/json
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Validation Report Ad Hoc Validate'
              example:
                valid: false
                fileType: string
                iatiVersion: string
                rulesetCommitSha: string
                codelistCommitSha: string
                orgIdPrefixFileName: string
                apiVersion: string
                summary:
                  critical: 0
                  error: 0
                  warning: 0
                errors:
                  - errors:
                      - errors:
                          - id: string
                            severity: string
                            message: string
                            codelist: string
                            context:
                              - text: string
                        category: string
                    identifier: string
                    title: string
components:
  schemas:
    No Body Error:
      type: object
      properties:
        error:
          type: string
      example:
        error: No body
    Malformed Body Error:
      type: object
      properties:
        error:
          type: string
      example:
        error: Body must be an application/xml string
    Validation Report Ad Hoc Validate:
      required:
        - valid
        - fileType
        - iatiVersion
        - rulesetCommitSha
        - codelistCommitSha
        - orgIdPrefixFileName
        - apiVersion
        - summary
        - errors
      type: object
      properties:
        valid:
          type: boolean
          description: Files with no critical severity errors are considered valid
        fileType:
          enum:
            - iati-activities
            - iati-organisations
          type: string
          description: The type of IATI file
        iatiVersion:
          type: string
          description: Version of the IATI Standard of the file
        rulesetCommitSha:
          type: string
          description: git commit sha of the ruleset used to create the validation report
        codelistCommitSha:
          type: string
          description: git commit sha of the codelist rules used to create the validation report
        orgIdPrefixFileName:
          type: string
          description: file name of org id prefixes from https://org-id.guide/download.json
        apiVersion:
          type: string
          description: version of the validator api
        summary:
          required:
            - critical
            - error
            - warning
          type: object
          properties:
            critical:
              type: integer
              description: Number of critical level validation errors with the file
            error:
              type: integer
              description: Number of error level validation errors with the file
            warning:
              type: integer
              description: Number of warning level validation errors with the file
        errors:
          type: array
          items:
            required:
              - errors
              - identifier
              - title
            type: object
            properties:
              errors:
                type: array
                items:
                  required:
                    - errors
                    - category
                  type: object
                  properties:
                    errors:
                      type: array
                      items:
                        required:
                          - id
                          - severity
                          - message
                          - context
                        type: object
                        properties:
                          id:
                            type: string
                            description: The unique identifier of the error
                          severity:
                            enum:
                              - critical
                              - danger
                              - warning
                            type: string
                            description: The severity level of the error
                          message:
                            type: string
                            description: The informational message about the validation error
                          codelist:
                            type: string
                            description: The codelist that is being validated against (if applicable)
                          context:
                            type: array
                            items:
                              required:
                                - text
                              type: object
                              properties:
                                text:
                                  type: string
                                  description: The context of the error
                    category:
                      enum:
                        - identifiers
                        - organisation
                        - information
                        - participating
                        - geo
                        - classifications
                        - financial
                        - documents
                        - relations
                        - performance
                      type: string
                      description: The category of the validation error
              identifier:
                type: string
                description: 'The activity''s iati-identifier for iati-activities files, organisation-identifier for iati-organisations file, or ''file'' for file level errors'
              title:
                type: string
                description: 'The activity''s title for iati-activities files, the organisation name for iati-organisations files, or ''File level errors'' for file level errors'
          description: 'array of errors, if empty the file has no errors'
      example:
        valid: false
        fileType: string
        iatiVersion: string
        rulesetCommitSha: string
        codelistCommitSha: string
        orgIdPrefixFileName: string
        apiVersion: string
        summary:
          critical: 0
          error: 0
          warning: 0
        errors:
          - errors:
              - errors:
                  - id: string
                    severity: string
                    message: string
                    codelist: string
                    context:
                      - text: string
                category: string
            identifier: string
            title: string
    Validation Report Published File:
      required:
        - registry_hash
        - registry_id
        - document_url
        - valid
        - report
      type: object
      properties:
        registry_hash:
          type: string
          description: hash of the file as defined by the IATI registry
        registry_id:
          type: string
          description: id of the file as defined by the IATI registry
        document_url:
          type: string
          description: url of the file as defined in the IATI registry
        valid:
          type: boolean
          description: Files with no critical severity errors are considered valid
        report:
          required:
            - valid
            - fileType
            - iatiVersion
            - rulesetCommitSha
            - codelistCommitSha
            - orgIdPrefixFileName
            - apiVersion
            - summary
            - errors
          type: object
          properties:
            valid:
              type: boolean
              description: Files with no critical severity errors are considered valid
            fileType:
              enum:
                - iati-activities
                - iati-organisations
              type: string
              description: The type of IATI file
            iatiVersion:
              type: string
              description: Version of the IATI Standard of the file
            rulesetCommitSha:
              type: string
              description: git commit sha of the ruleset used to create the validation report
            codelistCommitSha:
              type: string
              description: git commit sha of the codelist rules used to create the validation report
            orgIdPrefixFileName:
              type: string
              description: file name of org id prefixes from https://org-id.guide/download.json
            apiVersion:
              type: string
              description: version of the validator api
            summary:
              required:
                - critical
                - error
                - warning
              type: object
              properties:
                critical:
                  type: integer
                  description: Number of critical level validation errors with the file
                error:
                  type: integer
                  description: Number of error level validation errors with the file
                warning:
                  type: integer
                  description: Number of warning level validation errors with the file
            errors:
              type: array
              items:
                required:
                  - errors
                  - identifier
                  - title
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      required:
                        - errors
                        - category
                      type: object
                      properties:
                        errors:
                          type: array
                          items:
                            required:
                              - id
                              - severity
                              - message
                              - context
                            type: object
                            properties:
                              id:
                                type: string
                                description: The unique identifier of the error
                              severity:
                                enum:
                                  - critical
                                  - danger
                                  - warning
                                type: string
                                description: The severity level of the error
                              message:
                                type: string
                                description: The informational message about the validation error
                              codelist:
                                type: string
                                description: The codelist that is being validated against (if applicable)
                              context:
                                type: array
                                items:
                                  required:
                                    - text
                                  type: object
                                  properties:
                                    text:
                                      type: string
                                      description: The context of the error
                        category:
                          enum:
                            - identifiers
                            - organisation
                            - information
                            - participating
                            - geo
                            - classifications
                            - financial
                            - documents
                            - relations
                            - performance
                          type: string
                          description: The category of the validation error
                  identifier:
                    type: string
                    description: 'The activity''s iati-identifier for iati-activities files, organisation-identifier for iati-organisations file, or ''file'' for file level errors'
                  title:
                    type: string
                    description: 'The activity''s title for iati-activities files, the organisation name for iati-organisations files, or ''File level errors'' for file level errors'
              description: 'array of errors, if empty the file has no errors'
      example:
        registry_hash: string
        registry_id: string
        document_url: string
        valid: false
        report:
          valid: false
          fileType: string
          iatiVersion: string
          rulesetCommitSha: string
          codelistCommitSha: string
          orgIdPrefixFileName: string
          apiVersion: string
          summary:
            critical: 0
            error: 0
            warning: 0
          errors:
            - errors:
                - errors:
                    - id: string
                      severity: string
                      message: string
                      codelist: string
                      context:
                        - text: string
                  category: string
              identifier: string
              title: string
    Existing Report missing query parameter:
      type: object
      properties:
        client_error:
          type: string
      example:
        client_error: 'Either the id, url or hash of the document as obtained from the IATI Registry must be supplied as a GET parameter'
    Existing Report Not Found:
      type: object
      properties:
        client_error:
          type: string
      example:
        client_error: The requested report does not exist.
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]